import { K2_SE_PROFILE } from "../shared/profile.js";
import type { PrintSettings } from "../shared/settings.js";

function bool(value: boolean): string {
  return value ? "1" : "0";
}

function gcode(lines: string[]): string {
  return lines.join("\\n");
}

function fixed(value: number, digits = 3): string {
  return Number(value.toFixed(digits)).toString();
}

export function createPrusaConfig(settings: PrintSettings): string {
  const plate = K2_SE_PROFILE.buildVolume;
  const supportEnabled = bool(settings.supports);
  const skirtLoops = settings.adhesion === "skirt" ? settings.skirtLoops : 0;
  const brimWidth = settings.adhesion === "brim" ? settings.brimWidth : 0;

  const startGcode = gcode([
    "; K2 SE generic single-filament start",
    "M140 S[first_layer_bed_temperature]",
    "M104 S[first_layer_temperature]",
    "M190 S[first_layer_bed_temperature]",
    "M109 S[first_layer_temperature]",
    "G28",
    "G90",
    "M83",
    "G92 E0",
    "G1 Z0.28 F600",
    "G1 X5 Y5 F6000",
    "G1 X5 Y180 E15 F900",
    "G1 X8 Y180 F6000",
    "G1 X8 Y5 E30 F900",
    "G92 E0",
  ]);

  const endGcode = gcode([
    "; K2 SE generic end",
    "M104 S0",
    "M140 S0",
    "G91",
    "G1 E-2 F1800",
    "G1 Z10 F900",
    "G90",
    "G1 X0 Y215 F6000",
    "M84",
  ]);

  return [
    "# Generated by K2 SE Browser Slicer",
    "# Single-filament profile; no CFS or multi-material assumptions.",
    "printer_technology = FFF",
    `bed_shape = 0x0,${plate.x}x0,${plate.x}x${plate.y},0x${plate.y}`,
    `max_print_height = ${plate.z}`,
    `nozzle_diameter = ${fixed(settings.nozzleDiameter)}`,
    "extruders_count = 1",
    "single_extruder_multi_material = 0",
    "wipe_tower = 0",
    `gcode_flavor = ${K2_SE_PROFILE.gcodeFlavor}`,
    "use_relative_e_distances = 1",
    `start_gcode = ${startGcode}`,
    `end_gcode = ${endGcode}`,
    `layer_height = ${fixed(settings.layerHeight)}`,
    `first_layer_height = ${fixed(Math.max(settings.layerHeight, 0.18))}`,
    `perimeters = ${settings.walls}`,
    `top_solid_layers = ${settings.topLayers}`,
    `bottom_solid_layers = ${settings.bottomLayers}`,
    `fill_density = ${fixed(settings.infillDensity, 1)}%`,
    `fill_pattern = ${settings.infillPattern}`,
    `support_material = ${supportEnabled}`,
    `support_material_auto = ${supportEnabled}`,
    `support_material_threshold = ${settings.supportOverhang}`,
    `skirts = ${skirtLoops}`,
    "skirt_distance = 6",
    `brim_width = ${fixed(brimWidth, 1)}`,
    `temperature = ${settings.nozzleTemp}`,
    `first_layer_temperature = ${settings.firstLayerNozzleTemp}`,
    `bed_temperature = ${settings.bedTemp}`,
    `first_layer_bed_temperature = ${settings.firstLayerBedTemp}`,
    `filament_diameter = ${fixed(settings.filamentDiameter)}`,
    "filament_type = PLA",
    "filament_density = 1.24",
    `extrusion_multiplier = ${fixed(settings.flowRatio)}`,
    "retract_length = 0.8",
    "retract_speed = 40",
    "deretract_speed = 40",
    `first_layer_speed = ${settings.speeds.firstLayer}`,
    `external_perimeter_speed = ${settings.speeds.outerWall}`,
    `perimeter_speed = ${settings.speeds.innerWall}`,
    `infill_speed = ${settings.speeds.infill}`,
    `solid_infill_speed = ${Math.min(settings.speeds.infill, settings.speeds.innerWall)}`,
    `top_solid_infill_speed = ${Math.min(settings.speeds.outerWall, 120)}`,
    `support_material_speed = ${settings.speeds.support}`,
    `travel_speed = ${settings.speeds.travel}`,
    "max_print_speed = 500",
    "default_acceleration = 5000",
    "perimeter_acceleration = 4000",
    "infill_acceleration = 6000",
    "travel_acceleration = 8000",
    "avoid_crossing_curled_overhangs = 1",
    "complete_objects = 0",
    "",
  ].join("\n");
}
